name: swift-format
description: 'Lint and format by https://github.com/apple/swift-format'
inputs:
  configuration_file:
    required: false
    default: ''
  all_files:
    required: false
    default: 'false'
  auto_correct:
    required: false
    default: 'false'
  max_warnings:
    required: false
    default: -1

runs:
  using: node12
  main: index.js
