name: build

on:
  push:
    branches:
      - main
    paths:
      - Dockerfile
      - entrypoint.sh
      - .github/workflows/build.yml

jobs:
  docker:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      packages: write
    steps:
      -
        name: Checkout
        uses: actions/checkout@v6
      -
        name: Build and push
        uses: ./.github/actions/docker-build-push
        with:
          tags: ghcr.io/mtgto/swift-format-action:latest
